chart-dirs:
  - charts
validate-maintainers: true
check-version-increment: true
chart-yaml-schema: .devcontainer/ct/chart_schema.yaml
# Keep yamllint deterministic (provide a repo-local config if/when needed)
lint-conf: .devcontainer/ct/lintconf.yaml
