{{- if .Values.ingress.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.ingress.admin.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.admin.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.admin.ingressClassName }}
  ingressClassName: {{ .Values.ingress.admin.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.admin.hostname }}
    - host: {{ tpl .Values.ingress.admin.hostname $ | quote }}
      http:
        paths:
          {{- if .Values.ingress.admin.extraPaths }}
          {{- toYaml .Values.ingress.admin.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ tpl .Values.ingress.admin.path . | quote }}
            pathType: {{ .Values.ingress.admin.pathType }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "admin" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.ingress.admin.extraHosts }}
    - host: {{ tpl .name $ | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "admin" "context" $) | nindent 14 }}
    {{- end }}
    {{- if .Values.ingress.admin.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.admin.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or (and .Values.ingress.admin.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.admin.annotations )) .Values.ingress.admin.selfSigned)) .Values.ingress.admin.extraTls }}
  tls:
    {{- if and .Values.ingress.admin.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.admin.annotations )) .Values.ingress.admin.selfSigned) }}
    - hosts:
        - {{ tpl .Values.ingress.admin.hostname $ | quote }}
        {{- if and (or (.Values.ingress.admin.tlsWwwPrefix) (eq (index .Values.ingress.admin.annotations "nginx.ingress.kubernetes.io/from-to-www-redirect") "true" )) (not (contains "www." .Values.ingress.admin.hostname))  }}
        - {{ printf "www.%s" (tpl .Values.ingress.admin.hostname $) | quote }}
        {{- end }}
      secretName: {{ printf "%s-tls" (tpl .Values.ingress.admin.hostname $) }}
    {{- end }}
    {{- if .Values.ingress.admin.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ingress.admin.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
