{{- if and .Values.secrets.seed.enabled (not .Values.secrets.seed.existingSecret) }}
{{ $secretName := include "acapy.seed.secretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
  annotations:
    {{- if .Values.secrets.seed.retainOnUninstall }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  seed: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" ($secretName) "Key" "seed" "Length" 32) }}
{{- end }}
