{{- if .Values.postgres.enabled -}}
{{ $databaseSecretName := (include "endorser-service.db.secretName" .) }}
{{ $superuserPassword := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" "postgres-password" "Length" 32) }}
{{ $userPassword := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" (default "password" .Values.postgres.customUser.secretKeys.password) "Length" 32) }}
{{ $customAdminPassword := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $databaseSecretName "Key" (default "admin-password" .Values.postgres.customAdminUser.secretKeys.password) "Length" 32) }}
{{ $customAdminNameKey := default "admin-user" .Values.postgres.customAdminUser.secretKeys.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $databaseSecretName }}
  namespace: {{ .Release.Namespace | quote }}
  {{- $annotations := include "endorser-service.renderAnnotations" (dict "context" . "annotations" (ternary (dict "helm.sh/resource-policy" "keep") (dict) .Values.secrets.database.retainOnUninstall)) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "endorser-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  database: {{ (.Values.postgres.customUser.database | default .Values.postgres.customUser.name) | b64enc | quote }}
  password: {{ $userPassword }}
  postgres-password: {{ $superuserPassword }}
  user: {{ .Values.postgres.customUser.name | b64enc | quote }}
  {{ $customAdminNameKey }}: {{ .Values.postgres.customAdminUser.name | b64enc | quote }}
  {{ default "admin-password" .Values.postgres.customAdminUser.secretKeys.password }}: {{ $customAdminPassword }}
{{- end }}
