{{- if and .Values.proxy.enabled .Values.networkPolicy.enabled }}
{{- $proxyIngressNamespaceSelector := .Values.networkPolicy.proxy.ingress.namespaceSelector }}
{{- $proxyIngressPodSelector := .Values.networkPolicy.proxy.ingress.podSelector }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "endorser-service.fullname" . }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  {{- $annotations := include "endorser-service.renderAnnotations" (dict "context" .) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "endorser-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "endorser-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if or $proxyIngressNamespaceSelector $proxyIngressPodSelector }}
    - from:
        - {{ if $proxyIngressNamespaceSelector }}namespaceSelector:
            matchLabels:
              {{- toYaml $proxyIngressNamespaceSelector | nindent 14 }}
          {{ end }}{{- if $proxyIngressPodSelector }}podSelector:
            matchLabels:
              {{- toYaml $proxyIngressPodSelector | nindent 14 }}
          {{ end }}
      ports:
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.agent }}
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.admin }}
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.endorser }}
    {{- else }}
    - ports:
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.agent }}
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.admin }}
        - protocol: TCP
          port: {{ .Values.proxy.service.ports.endorser }}
    {{- end }}
    {{- with .Values.networkPolicy.proxy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.proxy.allowExternalEgress }}
    - {}
    {{- else }}
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- with .Values.networkPolicy.proxy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}
