autoscaling:
  enabled: false

acapy:
  autoscaling:
    enabled: false
  persistence:
    enabled: false
  postgres:
    persistence:
      enabled: false

mongodb:
  persistence:
    enabled: false
