{{- if .Values.acapy.enabled }}
{{ $webhookSecretName := (include "vc-authn-oidc.webhookSecretName" .) }}
{{ $apiSecretName := (include "vc-authn-oidc.apiSecretName" .) }}
{{ $controllerApiKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $apiSecretName "Key" "controllerApiKey" "Length" 32) }}
{{ $controllerUrl := printf "http://%s:%v/webhooks" (include "global.fullname" .) (.Values.service.port | int) }}
{{ $webhookUrl := printf "%s#%s" $controllerUrl ($controllerApiKey | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $webhookSecretName }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
    app.kubernetes.io/component: acapy
type: Opaque
data:
  ACAPY_WEBHOOK_URL: {{ $webhookUrl | b64enc | quote }}
{{- end }}
