apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global.fullname" . }}-controller-config
  labels: {{- include "vc-authn-oidc.labels" . | nindent 4 }}
data:
  sessiontimeout.json: |
    {{ .Values.controller.sessionTimeout.config | toJson }}
  user_variable_substitution.py: |
    {{ .Values.controller.userVariableSubsitution | nindent 4 }}
