{{- if (include "vc-authn-oidc.token.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vc-authn-oidc.token.secretName" . }}
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-token.pem: {{ include "vc-authn-oidc.token.jwtToken" . | b64enc | quote }}
{{- end }}
